### ISSUE TITLE
SD card initialization failed! Failed to open GIF file from SPIFFS!

### ISSUE THREAD

**Issue by venom19Rivas** [thelastoutpostworkshop/animated_gif#2]
I have follow and connected all as the video shows. without memory card is all correct, but once i tried to use memory card . I have the following isue...

load:0x3fff0030,len:1448
load:0x40078000,len:14844
ho 0 tail 12 room 4
load:0x40080400,len:4
load:0x40080404,len:3356
entry 0x4008059c
SD card initialization...
SD card initialization failed!
Failed to open GIF file from SPIFFS!

I have checked twice the connection, with multimeter to check connection. Also I bought a new memory card reader , use a different micro sd memory and the same issue. 
Please your help with this I have no more ideas or what to do.

**Comment by thelastoutpostworkshop** [comment]
In the TFT_espi example, try the basic ESP32_SDcard_jpeg example under "Generic" to see if it works.

**Comment by venom19Rivas** [comment]
I have checked it. ESP32_SDcard_jpeg it works. here the proof 

===============

 JPEG drawn in 5 ms 
===========================
Drawing file: /Baboon40.jpg
===========================
JPEG image info
===============
Width      :320
Height     :480
Components :1
MCU / row  :20
MCU / col  :30
Scan type  :4
MCU width  :16
MCU height :16
===============

 JPEG drawn in 184 ms 
===========================
Drawing file: /lena20k.jpg
===========================
JPEG image info
===============
Width      :320
Height     :480
Components :1
MCU / row  :20
MCU / col  :30
Scan type  :4
MCU width  :16
MCU height :16
===============

![WhatsApp Image 2024-08-08 at 1 13 29 PM](https://github.com/user-attachments/assets/ccfbf356-b06c-45e7-b700-fb8a703ce9ae)

**what could it be?  any suggestion to solve this?**

**Comment by thelastoutpostworkshop** [comment]
Maybe it is because DMA is used, make sure it is not in the GIFdraw,ino

**Comment by venom19Rivas** [comment]
please dear friend. Could you explain me how to do it? 

Im not sure how to do that 

Im using the code you use in the video. Here the code


#include <SD.h>
#include <SPI.h>
#include <FS.h>
#include <SPIFFS.h>
#include <TFT_eSPI.h>      // Install this library with the Arduino Library Manager
                           // Don't forget to configure the driver for the display!

#include <AnimatedGIF.h>   // Install this library with the Arduino Library Manager

#define SD_CS_PIN 12 // Chip Select Pin (CS) for SD card Reader

AnimatedGIF gif;
File gifFile;              // Global File object for the GIF file
TFT_eSPI tft = TFT_eSPI(); 

const char *filename = "/darthvader.gif";   // Change to load other gif files in images/GIF
void setup()
{
  Serial.begin(115200);
  tft.begin();
  tft.setRotation(2); // Adjust Rotation of your screen (0-3)
  tft.fillScreen(TFT_BLACK);

  // Initialize SD card
  Serial.println("SD card initialization...");
  if (!SD.begin(SD_CS_PIN))
  {
    Serial.println("SD card initialization failed!");
    return;
  }

  // Initialize SPIFFS
  Serial.println("Initialize SPIFFS...");
  if (!SPIFFS.begin(true))
  {
    Serial.println("SPIFFS initialization failed!");
  }

  // Reformmating the SPIFFS to have space if a large GIF is loaded
  // You could run out of SPIFFS storage space if you load more than one image or a large GIF
  // You can also increase the SPIFFS storage space by changing the partition of the ESP32
  //
  Serial.println("Formatting SPIFFS...");
  SPIFFS.format(); // This will erase all the files, change as needed, SPIFFs is non-volatile memory
  Serial.println("SPIFFS formatted successfully.");

  // Open GIF file from SD card
  Serial.println("Openning GIF file from SD card...");
  File sdFile = SD.open(filename);
  if (!sdFile)
  {
    Serial.println("Failed to open GIF file from SD card!");
    return;
  }

  // Create a file in SPIFFS to store the GIF
  File spiffsFile = SPIFFS.open(filename, FILE_WRITE, true);
  if (!spiffsFile)
  {
    Serial.println("Failed to copy GIF in SPIFFS!");
    return;
  }

  // Read the GIF from SD card and write to SPIFFS
  Serial.println("Copy GIF in SPIFFS...");
  byte buffer[512];
  while (sdFile.available())
  {
    int bytesRead = sdFile.read(buffer, sizeof(buffer));
    spiffsFile.write(buffer, bytesRead);
  }

  spiffsFile.close();
  sdFile.close();

  // Initialize the GIF
  Serial.println("Starting animation...");
  gif.begin(BIG_ENDIAN_PIXELS);
}

void loop()
{
  if (gif.open(filename, fileOpen, fileClose, fileRead, fileSeek, GIFDraw))
  {
    tft.startWrite(); // The TFT chip slect is locked low
    while (gif.playFrame(true, NULL))
    {
    }
    gif.close();
    tft.endWrite(); // Release TFT chip select for the SD Card Reader
  }
}

// Callbacks for file operations for the Animated GIF Lobrary
void *fileOpen(const char *filename, int32_t *pFileSize)
{
  gifFile = SPIFFS.open(filename, FILE_READ);
  *pFileSize = gifFile.size();
  if (!gifFile)
  {
    Serial.println("Failed to open GIF file from SPIFFS!");
  }
  return &gifFile;
}

void fileClose(void *pHandle)
{
  gifFile.close();
}

int32_t fileRead(GIFFILE *pFile, uint8_t *pBuf, int32_t iLen)
{
  int32_t iBytesRead;
  iBytesRead = iLen;
  if ((pFile->iSize - pFile->iPos) < iLen)
    iBytesRead = pFile->iSize - pFile->iPos;
  if (iBytesRead <= 0)
    return 0;

  gifFile.seek(pFile->iPos);
  int32_t bytesRead = gifFile.read(pBuf, iLen);
  pFile->iPos += iBytesRead;

  return bytesRead;
}

int32_t fileSeek(GIFFILE *pFile, int32_t iPosition)
{
  if (iPosition < 0)
    iPosition = 0;
  else if (iPosition >= pFile->iSize)
    iPosition = pFile->iSize - 1;
  pFile->iPos = iPosition;
  gifFile.seek(pFile->iPos);
  return iPosition;
}

**Comment by thelastoutpostworkshop** [comment]
If DMA is used, you will have a #define USE_DMA in GIFDraw.ino.
For example, in GIFDraw.ino the line in bold should not be executed:
#ifdef USE_DMA
  **uint16_t usTemp[2][BUFFER_SIZE]; // Global to support DMA use**
#else
  uint16_t usTemp[1][BUFFER_SIZE];    // Global to support DMA use
#endif

The other thing you can try, is add a call to SPI.begin, before SD.Begin:
 SPI.begin(TFT_CLK_PIN, TFT_MISO_PIN, TFT_MOSI_PIN, SD_CS_PIN);
if (!SD.begin(SD_CS_PIN))
{
Serial.println("SD card initialization failed!");
return;
}
for the pins passed to SPI.Begin, use the pins define in your setup in the TFT_eSPI library

**Comment by venom19Rivas** [comment]
Hello dear friend. first of all i want to thank you for your support. I really really appreciate it

I´ve followed your instructions 
1.- I commented the line you said and tested. It didnt work

/////////////////////////////////////////////////////////////////////////////////
#define DISPLAY_WIDTH  tft.width()
#define DISPLAY_HEIGHT tft.height()
#define BUFFER_SIZE 256            // Optimum is >= GIF width or integral division of width

#ifdef USE_DMA
// uint16_t usTemp[2][BUFFER_SIZE]; // Global to support DMA use
#else
 uint16_t usTemp[1][BUFFER_SIZE];    // Global to support DMA use
#endif
bool     dmaBuf = 0;
.
.
.
////////////////////////////////////////////////////////////////////////////////////

2.- I uncommented the lines of the user setup of TFT espi library and included it in the main code
/////////////////////////////////////////////////////////////////////////////////////////
  #include <SD.h>
#include <SPI.h>
#include <FS.h>
#include <SPIFFS.h>
#include <TFT_eSPI.h>      // Install this library with the Arduino Library Manager
                           // Don't forget to configure the driver for the display!

#include <AnimatedGIF.h>   // Install this library with the Arduino Library Manager

#define SD_CS_PIN 12 // Chip Select Pin (CS) for SD card Reader
#define TFT_MOSI 23 // In some display driver board, it might be written as "SDA" and so on.
#define TFT_SCLK 18
#define TFT_CS   15  // Chip select control pin
#define TFT_DC   2  // Data Command control pin
#define TFT_RST  4  // Reset pin (could connect to Arduino RESET pin)


AnimatedGIF gif;
File gifFile;              // Global File object for the GIF file
TFT_eSPI tft = TFT_eSPI(); 

const char *filename = "/darthvader.gif";   // Change to load other gif files in images/GIF
void setup()
{
  Serial.begin(115200);
  tft.begin();
  tft.setRotation(2); // Adjust Rotation of your screen (0-3)
  tft.fillScreen(TFT_BLACK);

  // Initialize SD card
  Serial.println("SD card initialization...");
  SPI.begin(TFT_SCLK,TFT_MOSI,SD_CS_PIN);
  if (!SD.begin(SD_CS_PIN))
  {
    Serial.println("SD card initialization failed!");
    return;
  }
.
.
.
////////////////////////////////////////////////////////////////////////////

I have the same issue... any suggestion ???

or perhaps may you send all your codes of this project.
Because in the step where you enter the espi libraries and create a new ino user setup to modify, I wasnt able to do it. What I did, was to directly enter the txt file and modify it (because when i tried to follow the steps in your video, creating un new ino just a new txt file were created and there was no mode to make it as a .ino file )

**Comment by thelastoutpostworkshop** [comment]
Your SPI.begin has not the correct parameters, the MISO pin is missing.
The parameters are : SPI.begin(TFT_CLK_PIN, TFT_MISO_PIN, TFT_MOSI_PIN, SD_CS_PIN);

**Comment by venom19Rivas** [comment]
Yes i noticed it. I didnt added it because tft display im using hasnt that pin. 

![IPS-LCD-1 28-240x240-Round-Display-GC9A01-Round-PCB-Connections](https://github.com/user-attachments/assets/69ce7766-f835-456e-bfbd-120b30cd567a)

which pin should MISO PIN be?

**Comment by thelastoutpostworkshop** [comment]
it's for the SD Card, it has a MOSI pin

**Comment by venom19Rivas** [comment]
I´ve added the lines and checked all connections.

This is the modified code:

#include <SD.h>
#include <SPI.h>
#include <FS.h>
#include <SPIFFS.h>
#include <TFT_eSPI.h>      // Install this library with the Arduino Library Manager
                           // Don't forget to configure the driver for the display!

#include <AnimatedGIF.h>   // Install this library with the Arduino Library Manager

#define SD_CS_PIN 12 // Chip Select Pin (CS) for SD card Reader
#define TFT_MOSI 23 // In some display driver board, it might be written as "SDA" and so on.
#define TFT_MISO 19
#define TFT_SCLK 18
#define TFT_CS   15  // Chip select control pin
#define TFT_DC   2  // Data Command control pin
#define TFT_RST  4  // Reset pin (could connect to Arduino RESET pin)




AnimatedGIF gif;
File gifFile;              // Global File object for the GIF file
TFT_eSPI tft = TFT_eSPI(); 

const char *filename = "/darthvader.gif";   // Change to load other gif files in images/GIF
void setup()
{
  Serial.begin(115200);
  tft.begin();
  tft.setRotation(2); // Adjust Rotation of your screen (0-3)
  tft.fillScreen(TFT_BLACK);

  // Initialize SD card
  Serial.println("SD card initialization...");
  SPI.begin(TFT_SCLK,TFT_MOSI,TFT_MISO,SD_CS_PIN);
  if (!SD.begin(SD_CS_PIN))
  {
    Serial.println("SD card initialization failed!");
    return;
  }
.
.
.
.

It didnt work. still the same issue.
What else could it be ?
Perhaps may you send me your codes, so I can try with them ?

**Comment by thelastoutpostworkshop** [comment]
The code is the one in the repo.
Show me a picture of your wiring.

**Comment by venom19Rivas** [comment]
Ok ive used the code from the repository,
this is my circuit

![WhatsApp Image 2024-08-11 at 12 54 45 PM](https://github.com/user-attachments/assets/ebc627f4-92ba-40c3-b308-53448ac4bb62)

**Comment by thelastoutpostworkshop** [comment]
Your wiring is ok, except when you took the picture you probably misaligned your display, or its the angle of the picture.
I am not sure that placing the definitions of the pins in the main sketch is ok.
You should have them defined in  <User_Setups/Setup46_GC9A01_ESP32.h>, you have to uncomment it in <User_Setup_Select.h>.
Review my tutorial on how to do it.

**Comment by thelastoutpostworkshop** [comment]
Here is the content of <User_Setups/Setup46_GC9A01_ESP32.h> : 
#define USER_SETUP_ID 46

#define GC9A01_DRIVER

#define TFT_MISO -1
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS    15  // Chip select control pin
#define TFT_DC    2  // Data Command control pin
#define TFT_RST   4  // Reset pin (could connect to RST pin)
//#define TFT_RST  -1  // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts
#define SMOOTH_FONT

#define SPI_FREQUENCY  20000000

#define SPI_READ_FREQUENCY  20000000

#define SPI_TOUCH_FREQUENCY  2500000

// #define SUPPORT_TRANSACTIONS

**Comment by venom19Rivas** [comment]
i think its the camera angle. here more pictures, hoping a better look of it

![WhatsApp Image 2024-08-12 at 12 23 59 PM (1)](https://github.com/user-attachments/assets/ff22b712-2f5b-4611-bb34-d1cd1d251957)
![WhatsApp Image 2024-08-12 at 12 23 59 PM](https://github.com/user-attachments/assets/a0625cde-0b04-4dc5-b8f6-a1036f05c1c9)

--------------------------------------------------------------------------------------------------------------
also I took a screen shot user setup config.



![Sin título](https://github.com/user-attachments/assets/035746bf-698a-4165-b20a-87cc306bd759)


perhaps you could see something wrong that I couldnt see

**Comment by thelastoutpostworkshop** [comment]
You have to add #define TFT_RST 4, not -1, the TFT requires it

**Comment by venom19Rivas** [comment]
Hello dear friend, may you please send me your raw nostromo program, 
so I can put a different text messages ?

**Comment by thelastoutpostworkshop** [comment]
Sorry, but I do not have the raw file anymore.
