### ISSUE TITLE
screen and SD card use same pins

### ISSUE THREAD

**Issue by LambMediaGroup** [thelastoutpostworkshop/animated_gif#4]
Hi

I've just realised that the screen and the SD card use the same pins in your tutorial. Do I just connect both devices to one pin or is there a way of changing what pins one of the devices uses?

**Comment by thelastoutpostworkshop** [comment]
They are both connected to the SPI bus, the only pin that need to be different is the CS (Chip Select Pin)

**Comment by mateus23-gacor** [comment]
hello owner, why my SD card initialization failed!, i make sure the pin i use is correct
